### ISSUE TITLE
remove default value for repo?

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/beavis-ci#1]
@drphilmarshall I see that you have changed the default repo to
```bash
repo=$( git config --get remote.origin.url | cut -d':' -f2 | cut -d'.' -f1 )
```
I wonder if we should just remove default repo value (i.e., make it a required input). 

The workflow I have in my mind is that people would clone this repo, not within but outwith any repos they may want to render, and run like
```bash
.beavis-ci LSSTDESC/DC2-analysis
.beavis-ci LSSTDESC/DC2-production
.beavis-ci LSSTDESC/...
```
I think that's cleaner way to use this tool now that it is standalone. Thoughts?

**Comment by drphilmarshall** [comment]
Sure! I like that. I just completed all the initial commits (including LICENSE and README) so let's start improving it :-)  I'll take this one on right away.
